### ISSUE TITLE
Add One-Click Deploy Buttons

### ISSUE THREAD

**Issue by jonmarkgo** [codeRIT/hackathon-manager#158]
You have some great docs on how to deploy to various services, but to make it even easier I'd love to see something like a Deploy to Heroku button (one click deploy w/ form-fill in for ENV vars) https://devcenter.heroku.com/articles/heroku-button

Not sure if other cloud providers have something similar, but if so that could be great too.

[Edit: Looks like Azure has another thing, just to give devs multiple options for easy one-click deploy: [https://azure.microsoft.com/en-us/blog/deploy-to-azure-button-for-azure-websites-2/](https://azure.microsoft.com/en-us/blog/deploy-to-azure-button-for-azure-websites-2/) ]

**Comment by sman591** [comment]
Thanks! I added the Deploy to Heroku Burton on the Heroku deployment page, but clearly there’s value in having it on the homepage & readme too.

Haven’t used Azure as much but good to know they have a similar solution, I’ll try it out and put up some docs for it as well 👍

**Comment by sman591** [comment]
Added the Deploy to Heroku button to the homepage 🚀 

<img width="1067" alt="Screenshot 2019-05-24 10 02 23" src="https://user-images.githubusercontent.com/1441807/58375245-572eaf80-7f1c-11e9-85d8-a7847317d653.png">

I spent a few hours trying out Azure, but I can't get the app to deploy (gets stuck during the `bundle install` process at compiling the SASS gem, presumably because this is a slow process and hits a timeout). I've found very little docs online for troubleshooting this, so I'm going to stick with just Heroku for one-click deploys for now.
